apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-test-app

resources:
  - manifests.yaml

configMapGenerator:
  - name: app-config
    files:
      - app.conf
  - name: app-envvars
    envs:
      - envvars.env
