apiVersion: v1
kind: Namespace
metadata:
  name: kustomize-test-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-test-app
  labels:
    app.kubernetes.io/name: kubernetes-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-test-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 961fb97a3978aa209545dd85a9ca86e96c838d27b1890397b055115438627814
      labels:
        app.kubernetes.io/name: kubernetes-test-app
    spec:
      containers:
        - name: test-app
          image: busybox
          args:
            - "sleep"
            - "100000000"
          envFrom:
            - configMapRef:
                name: app-envvars
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /app/config
            name: app-conf
      volumes:
      - name: app-conf
        configMap:
          name: app-config
